//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationISPDn
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISPDnObem
    {
        public ISPDnObem()
        {
            this.ISPDnOperator = new HashSet<ISPDnOperator>();
        }
    
        public int ISPDnObemID { get; set; }
        public string ISPDnObemOpisanie { get; set; }
    
        public virtual ICollection<ISPDnOperator> ISPDnOperator { get; set; }
    }
}
