//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationISPDn
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISPDnOperator
    {
        public ISPDnOperator()
        {
            this.MnogieISPDnSubj = new HashSet<MnogieISPDnSubj>();
            this.MnogieOpasnUgrozIS = new HashSet<MnogieOpasnUgrozIS>();
            this.MnogieRealizUgroz = new HashSet<MnogieRealizUgroz>();
            this.MnogieUgrozaActual = new HashSet<MnogieUgrozaActual>();
            this.MnogieVerUgrozIS = new HashSet<MnogieVerUgrozIS>();
            this.CeliObrabotkiPD = new HashSet<CeliObrabotkiPD>();
            this.ISPDnHarakteristikIshod = new HashSet<ISPDnHarakteristikIshod>();
            this.KategoryPd = new HashSet<KategoryPd>();
            this.RabotnikiOrg = new HashSet<RabotnikiOrg>();
            this.KategoryPdBio = new HashSet<KategoryPdBio>();
            this.KategoryPdDop = new HashSet<KategoryPdDop>();
            this.KategoryPdSpec = new HashSet<KategoryPdSpec>();
        }
    
        public int ISPDnOperatorID { get; set; }
        public string ISPDnOperatorName { get; set; }
        public Nullable<int> OrgOperatorID { get; set; }
        public Nullable<int> ISPDnKategoryID { get; set; }
        public Nullable<int> ISPDnObemID { get; set; }
        public Nullable<int> ISPDnKlassID { get; set; }
        public Nullable<int> ISPDnIshodZashitaID { get; set; }
        public Nullable<int> ISPDnTipSpecialID { get; set; }
        public Nullable<int> ISPDnTipModeli { get; set; }
    
        public virtual ISPDnIshodZashita ISPDnIshodZashita { get; set; }
        public virtual ISPDnKategory ISPDnKategory { get; set; }
        public virtual ISPDnKlass ISPDnKlass { get; set; }
        public virtual ISPDnObem ISPDnObem { get; set; }
        public virtual ISPDnTipSpecial ISPDnTipSpecial { get; set; }
        public virtual OrgOperator OrgOperator { get; set; }
        public virtual ICollection<MnogieISPDnSubj> MnogieISPDnSubj { get; set; }
        public virtual ICollection<MnogieOpasnUgrozIS> MnogieOpasnUgrozIS { get; set; }
        public virtual ICollection<MnogieRealizUgroz> MnogieRealizUgroz { get; set; }
        public virtual ICollection<MnogieUgrozaActual> MnogieUgrozaActual { get; set; }
        public virtual ICollection<MnogieVerUgrozIS> MnogieVerUgrozIS { get; set; }
        public virtual ICollection<CeliObrabotkiPD> CeliObrabotkiPD { get; set; }
        public virtual ICollection<ISPDnHarakteristikIshod> ISPDnHarakteristikIshod { get; set; }
        public virtual ICollection<KategoryPd> KategoryPd { get; set; }
        public virtual ICollection<RabotnikiOrg> RabotnikiOrg { get; set; }
        public virtual ICollection<KategoryPdBio> KategoryPdBio { get; set; }
        public virtual ICollection<KategoryPdDop> KategoryPdDop { get; set; }
        public virtual ICollection<KategoryPdSpec> KategoryPdSpec { get; set; }
    }
}
