//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationISPDn
{
    using System;
    using System.Collections.Generic;
    
    public partial class KategoryPdSpec
    {
        public KategoryPdSpec()
        {
            this.OtdelOrg = new HashSet<OtdelOrg>();
            this.ISPDnOperator = new HashSet<ISPDnOperator>();
        }
    
        public int KategoryPdSpecID { get; set; }
        public string KategoryPdSpecName { get; set; }
    
        public virtual ICollection<OtdelOrg> OtdelOrg { get; set; }
        public virtual ICollection<ISPDnOperator> ISPDnOperator { get; set; }
    }
}
