//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationISPDn
{
    using System;
    using System.Collections.Generic;
    
    public partial class KategorySubj
    {
        public KategorySubj()
        {
            this.MnogieISPDnSubj = new HashSet<MnogieISPDnSubj>();
            this.OtdelOrg = new HashSet<OtdelOrg>();
        }
    
        public int KategorySubjID { get; set; }
        public string KategorySubjName { get; set; }
        public bool KategorySubjSelect { get; set; }
        public Nullable<int> OrgOperatorID { get; set; }
    
        public virtual OrgOperator OrgOperator { get; set; }
        public virtual ICollection<MnogieISPDnSubj> MnogieISPDnSubj { get; set; }
        public virtual ICollection<OtdelOrg> OtdelOrg { get; set; }
    }
}
