//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationISPDn
{
    using System;
    using System.Collections.Generic;
    
    public partial class KategoryPdDop
    {
        public KategoryPdDop()
        {
            this.OtdelOrg = new HashSet<OtdelOrg>();
            this.ISPDnOperator = new HashSet<ISPDnOperator>();
        }
    
        public int KategoryPdDopID { get; set; }
        public string KategoryPdDopName { get; set; }
        public bool KategoryPdDopSelect { get; set; }
        public Nullable<int> OrgOperatorID { get; set; }
    
        public virtual OrgOperator OrgOperator { get; set; }
        public virtual ICollection<OtdelOrg> OtdelOrg { get; set; }
        public virtual ICollection<ISPDnOperator> ISPDnOperator { get; set; }
    }
}
