//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationISPDn
{
    using System;
    using System.Collections.Generic;
    
    public partial class MnogieUgrozaActual
    {
        public int NazvanieUgrozID { get; set; }
        public int ISPDnOperatorID { get; set; }
        public Nullable<int> ActualnostID { get; set; }
    
        public virtual Actualnost Actualnost { get; set; }
        public virtual ISPDnOperator ISPDnOperator { get; set; }
        public virtual NazvanieUgroz NazvanieUgroz { get; set; }
    }
}
