//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationISPDn
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ISPDnBDSQLEntities : DbContext
    {
        public ISPDnBDSQLEntities()
            : base("name=ISPDnBDSQLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Actualnost> Actualnost { get; set; }
        public DbSet<CeliObrabotkiPD> CeliObrabotkiPD { get; set; }
        public DbSet<ISPDnHarakteristikIshod> ISPDnHarakteristikIshod { get; set; }
        public DbSet<ISPDnIshodZashita> ISPDnIshodZashita { get; set; }
        public DbSet<ISPDnKategory> ISPDnKategory { get; set; }
        public DbSet<ISPDnKlass> ISPDnKlass { get; set; }
        public DbSet<ISPDnObem> ISPDnObem { get; set; }
        public DbSet<ISPDnOperator> ISPDnOperator { get; set; }
        public DbSet<ISPDnTipSpecial> ISPDnTipSpecial { get; set; }
        public DbSet<KategoryPd> KategoryPd { get; set; }
        public DbSet<KategoryPdBio> KategoryPdBio { get; set; }
        public DbSet<KategoryPdDop> KategoryPdDop { get; set; }
        public DbSet<KategoryPdSpec> KategoryPdSpec { get; set; }
        public DbSet<KategorySubj> KategorySubj { get; set; }
        public DbSet<MnogieISPDnSubj> MnogieISPDnSubj { get; set; }
        public DbSet<MnogieOpasnUgrozIS> MnogieOpasnUgrozIS { get; set; }
        public DbSet<MnogieRealizUgroz> MnogieRealizUgroz { get; set; }
        public DbSet<MnogieUgrozaActual> MnogieUgrozaActual { get; set; }
        public DbSet<MnogieVerUgrozIS> MnogieVerUgrozIS { get; set; }
        public DbSet<NazvanieUgroz> NazvanieUgroz { get; set; }
        public DbSet<OpasnostUgroz> OpasnostUgroz { get; set; }
        public DbSet<OrgOperator> OrgOperator { get; set; }
        public DbSet<OtdelOrg> OtdelOrg { get; set; }
        public DbSet<RabotnikiOrg> RabotnikiOrg { get; set; }
        public DbSet<RealizationUgroz> RealizationUgroz { get; set; }
        public DbSet<VeroyatnostUgroz> VeroyatnostUgroz { get; set; }
        public DbSet<VidIshodHarakteristik> VidIshodHarakteristik { get; set; }
        public DbSet<VidUgroz> VidUgroz { get; set; }
    }
}
