//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationISPDn
{
    using System;
    using System.Collections.Generic;
    
    public partial class NazvanieUgroz
    {
        public NazvanieUgroz()
        {
            this.MnogieOpasnUgrozIS = new HashSet<MnogieOpasnUgrozIS>();
            this.MnogieRealizUgroz = new HashSet<MnogieRealizUgroz>();
            this.MnogieUgrozaActual = new HashSet<MnogieUgrozaActual>();
            this.MnogieVerUgrozIS = new HashSet<MnogieVerUgrozIS>();
        }
    
        public int NazvanieUgrozID { get; set; }
        public string NazvanieUgrozName { get; set; }
        public Nullable<int> VidUgrozID { get; set; }
        public bool C1 { get; set; }
        public bool C2 { get; set; }
        public bool C3 { get; set; }
        public bool C4 { get; set; }
    
        public virtual ICollection<MnogieOpasnUgrozIS> MnogieOpasnUgrozIS { get; set; }
        public virtual ICollection<MnogieRealizUgroz> MnogieRealizUgroz { get; set; }
        public virtual ICollection<MnogieUgrozaActual> MnogieUgrozaActual { get; set; }
        public virtual ICollection<MnogieVerUgrozIS> MnogieVerUgrozIS { get; set; }
        public virtual VidUgroz VidUgroz { get; set; }
    }
}
