//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationISPDn
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpasnostUgroz
    {
        public OpasnostUgroz()
        {
            this.MnogieOpasnUgrozIS = new HashSet<MnogieOpasnUgrozIS>();
        }
    
        public int OpasnostUgrozID { get; set; }
        public string OpasnostUgrozName { get; set; }
    
        public virtual ICollection<MnogieOpasnUgrozIS> MnogieOpasnUgrozIS { get; set; }
    }
}
