//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationISPDn
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgOperator
    {
        public OrgOperator()
        {
            this.CeliObrabotkiPD = new HashSet<CeliObrabotkiPD>();
            this.ISPDnOperator = new HashSet<ISPDnOperator>();
            this.KategoryPdBio = new HashSet<KategoryPdBio>();
            this.KategoryPdDop = new HashSet<KategoryPdDop>();
            this.KategorySubj = new HashSet<KategorySubj>();
            this.OtdelOrg = new HashSet<OtdelOrg>();
            this.RabotnikiOrg = new HashSet<RabotnikiOrg>();
        }
    
        public int OrgOperatorID { get; set; }
        public string OrgOperatorKratkName { get; set; }
        public string OrgOperatorFullName { get; set; }
        public string OrgOperatorINN { get; set; }
        public string OrgOperatorRukovoditelName { get; set; }
        public string OrgOperatorRukovoditelDolgn { get; set; }
        public string OrgOperatorAdress { get; set; }
        public string UserID { get; set; }
    
        public virtual ICollection<CeliObrabotkiPD> CeliObrabotkiPD { get; set; }
        public virtual ICollection<ISPDnOperator> ISPDnOperator { get; set; }
        public virtual ICollection<KategoryPdBio> KategoryPdBio { get; set; }
        public virtual ICollection<KategoryPdDop> KategoryPdDop { get; set; }
        public virtual ICollection<KategorySubj> KategorySubj { get; set; }
        public virtual ICollection<OtdelOrg> OtdelOrg { get; set; }
        public virtual ICollection<RabotnikiOrg> RabotnikiOrg { get; set; }
    }
}
