//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationISPDn
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtdelOrg
    {
        public OtdelOrg()
        {
            this.CeliObrabotkiPD = new HashSet<CeliObrabotkiPD>();
            this.KategoryPdSpec = new HashSet<KategoryPdSpec>();
            this.KategoryPdBio = new HashSet<KategoryPdBio>();
            this.KategoryPdDop = new HashSet<KategoryPdDop>();
            this.KategoryPd = new HashSet<KategoryPd>();
            this.KategorySubj = new HashSet<KategorySubj>();
            this.RabotnikiOrg = new HashSet<RabotnikiOrg>();
        }
    
        public int OtdelOrgID { get; set; }
        public string OtdelOrgName { get; set; }
        public Nullable<int> OrgOperatorID { get; set; }
    
        public virtual OrgOperator OrgOperator { get; set; }
        public virtual ICollection<CeliObrabotkiPD> CeliObrabotkiPD { get; set; }
        public virtual ICollection<KategoryPdSpec> KategoryPdSpec { get; set; }
        public virtual ICollection<KategoryPdBio> KategoryPdBio { get; set; }
        public virtual ICollection<KategoryPdDop> KategoryPdDop { get; set; }
        public virtual ICollection<KategoryPd> KategoryPd { get; set; }
        public virtual ICollection<KategorySubj> KategorySubj { get; set; }
        public virtual ICollection<RabotnikiOrg> RabotnikiOrg { get; set; }
    }
}
