//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationISPDn
{
    using System;
    using System.Collections.Generic;
    
    public partial class RabotnikiOrg
    {
        public RabotnikiOrg()
        {
            this.ISPDnOperator = new HashSet<ISPDnOperator>();
            this.OtdelOrg = new HashSet<OtdelOrg>();
        }
    
        public int RabotnikiOrgID { get; set; }
        public string RabotnikiOrgFio { get; set; }
        public string RabotnikiOrgDolgn { get; set; }
        public bool RabotnikiOrgSelect { get; set; }
        public Nullable<int> OrgOperatorID { get; set; }
    
        public virtual OrgOperator OrgOperator { get; set; }
        public virtual ICollection<ISPDnOperator> ISPDnOperator { get; set; }
        public virtual ICollection<OtdelOrg> OtdelOrg { get; set; }
    }
}
