//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationISPDn
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealizationUgroz
    {
        public RealizationUgroz()
        {
            this.MnogieRealizUgroz = new HashSet<MnogieRealizUgroz>();
        }
    
        public int RealizationUgrozID { get; set; }
        public string RealizationUgrozName { get; set; }
        public Nullable<int> RealizationUgrozKof { get; set; }
    
        public virtual ICollection<MnogieRealizUgroz> MnogieRealizUgroz { get; set; }
    }
}
