//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationISPDn
{
    using System;
    using System.Collections.Generic;
    
    public partial class VidIshodHarakteristik
    {
        public VidIshodHarakteristik()
        {
            this.ISPDnHarakteristikIshod = new HashSet<ISPDnHarakteristikIshod>();
        }
    
        public int VidIshodHarakteristikID { get; set; }
        public string VidIshodHarakteristikName { get; set; }
    
        public virtual ICollection<ISPDnHarakteristikIshod> ISPDnHarakteristikIshod { get; set; }
    }
}
