//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationISPDn
{
    using System;
    using System.Collections.Generic;
    
    public partial class VidUgroz
    {
        public VidUgroz()
        {
            this.NazvanieUgroz = new HashSet<NazvanieUgroz>();
        }
    
        public int VidUgrozID { get; set; }
        public string VidUgrozName { get; set; }
    
        public virtual ICollection<NazvanieUgroz> NazvanieUgroz { get; set; }
    }
}
